baseURL = "https://reference.groupdocs.com/tutorials/editor"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://reference.groupdocs.com/?prefix=tutorials/editor/&region=us-west-2"
